@component('mail::message')
{{$name}}さん<br>
{{$date}}&emsp;{{$time}}&emsp;に{{$shop}}の予約をいただいております。<br>
@if($recommendation>0)
{{$hc}}名様分のおすすめコース（事前決済）をいただいております。
@endif
<br>
忘れずにお越しください。
@endcomponent